services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: simple-cart-mailpit
    restart: unless-stopped
    ports:
      - '${MAIL_PORT:-1025}:1025' # SMTP server
      - '${MAIL_WEB_PORT:-8025}:8025' # Web UI
    volumes:
      - mailpit_data:/data

volumes:
  mailpit_data:
    driver: local
